name: pdf_chatbot_env
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - python=3.10
  - numpy=1.24.3
  - pandas=2.1.4
  - scikit-learn=1.3.0
  - nltk=3.8.1
  - textstat=0.7.3
  - python-docx=0.8.11
  - openpyxl=3.1.2
  - pytorch=2.0.1
  - torchvision
  - torchaudio
  - pip
